# Generated by Django 5.2.7 on 2025-11-14 21:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='reviews_organization_1_5',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='organization',
            new_name='responsibility',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('responsibility__gte', 1), ('responsibility__lte', 5)), name='reviews_responsibility_1_5'),
        ),
    ]
