# Generated by Django 5.2.7 on 2025-11-28 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_reviews_organization_1_5_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_user_id_79db63_idx',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['owner'], name='reviews_owner_i_ca5314_idx'),
        ),
    ]
